### ISSUE TITLE
StatusCode when trying to remove a nonexistent ID

### ISSUE THREAD

**Issue by fabriciofs** [viniciusbo/hapi-suricate#1]
Performing tests, I verified that when asking to remove, for example a user, that does not exist is returned a statusCode 200, the correct would not return a 404

**Comment by viniciusbo** [comment]
Thanks for pointing that out. Actually this behavior is dicted by Mongoose. Since this lib is intended to be a minimal layer on top of Mongoose, there are no plans for implementing that kind of verification.

If you really need it, you should do it using this approach: https://github.com/viniciusbo/hapi-suricate#using-with-your-own-route-handlers (calling `handler.findOne` and then `handler.remove`)
